version: '3.4'

services:
  db:
    container_name: mysql_toy
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD : "pass"
      MYSQL_USER : "juyoung"
      MYSQL_PASSWORD : "pass"
      MYSQL_DATABASE : "toydb"
    volumes:
      -./volumes/mysql:/var/lib/mysql
