version: '3.6'

services:
  db:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD : "pass"
      MYSQL_USER : "juyoung"
      MYSQL_PASSWORD : "pass"
      MYSQL_DATABASE: "toy"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
