spring:
  profiles:
    active: local

  devtools:
    livereload:
      enabled: true

# security
my-app:
  auth:
    client-id: myApp
    client-secret: secret
  fixture:
    user-id: manager@gmail.com
    user-password: pass
