spring:
  profiles:
    active: local

  devtools:
    livereload:
      enabled: true

# security
my-app:
  clientId: myApp
  client-secret: secret
  user-id: manager@gmail.com
  user-password: pass
