spring:
  profiles:
    active: local

  devtools:
    livereload:
      enabled: true

# security
my-app:
  auth:
    client-id: myApp
    client-secret: secret
    jwt-info:
      secret: HS123
      expiration-in-ms: 360000
  admin-id: admin@email.com
  admin-password: admin
  user-id: user@email.com
  user-password: user

