spring:
  datasource:
    url: jdbc:mysql://localhost:3306/toy
    username: juyoung
    password: pass
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true