spring:
  datasource:
    url: jdbc:mysql://localhost:3306/toy
    username: juyoung
    password: pass
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        show_seq: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.security.oauth2.jwt: DEBUG