spring:
  profiles:
    active: local

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 434541373271-h977ssvpjlv003tdkfof6f49pqg8fsqr.apps.googleusercontent.com
            client-secret: d9k1lSwtPwrfHBtpwrp-fTac
            scope: email, profile
            redirect-uri-template: "{baseUrl}/oauth2/callback/{registrationId}"

  devtools:
    livereload:
      enabled: true

# security
my-app:
  auth:
    jwt:
      secret: HS123
      expirationInMs: 360000
  clientId: myApp
  clientSecret: secret
  admin-id: admin@email.com
  admin-password: admin
  user-id: user@email.com
  user-password: user

